version: '3.1'

services:
  my-webgl-game:
    image: nginx:latest
    container_name: my-webgl-game
    ports:
      - "80:80"
    volumes:
      - /unity/Build-WebGL:/usr/share/nginx/html:ro
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

